const DOCTOR_ONBOARDING_STEPS = [
  {
    description: "",
    component: "profile",
    isFinal: false,
    label: "Public Profile",
    order: 0,
    slug: "doctor-profile",
    title: "Public Profile",
  },
  {
    description: "",
    component: "profession",
    isFinal: false,
    label: "Professional Information",
    order: 1,
    slug: "doctor-profession",
    title: "Professional Information",
  },
  {
    description: "",
    component: "doctor-contract",
    isFinal: false,
    label: "Contract",
    order: 2,
    slug: "doctor-contract",
    title: "Contract",
  },
  {
    description: "",
    component: "review",
    isFinal: true,
    label: "Review and Confirm",
    order: 3,
    slug: "doctor-review",
    title: "Review and Confirm",
  },
  {
    description: "",
    component: "final",
    isFinal: true,
    label: "Complete",
    order: 4,
    slug: "doctor-complete",
    title: "Complete",
  },
];

const PATIENT_ONBOARDING_STEPS = [
  {
    description: "",
    component: "personal-data-form",
    isFinal: false,
    label: "Personal Information",
    order: 0,
    slug: "patient-personal-data-form",
    title: "Personal Information",
  },
  {
    description: "",
    component: "contacts",
    isFinal: false,
    label: "Contact Information",
    order: 1,
    slug: "patient-contacts",
    title: "Contact Information",
  },
  {
    description: "",
    component: "healthcard",
    isFinal: false,
    label: "Add Health Card Information",
    order: 2,
    slug: "patient-healthcard",
    title: "Add Health Card Information",
  },
  {
    description: "",
    component: "healthcard",
    isFinal: false,
    label: "Add Health Card Information",
    order: 2,
    slug: "emergency-contacts",
    title: "Add Health Card Information",
  },
  {
    description: "",
    component: "review",
    isFinal: true,
    label: "Review & Confirm",
    order: 3,
    slug: "patient-review",
    title: "Review & Confirm",
  },
  {
    description: "",
    component: "final",
    isFinal: true,
    label: "Done",
    order: 4,
    slug: "complete-patient",
    title: "You are all set and ready to book doctors!",
  },
];

export const STEPPERS = [
  {
    description: "",
    name: "Patient onboarding",
    slug: "patient",
    stepperSteps: PATIENT_ONBOARDING_STEPS,
    stepsOrderBySlugs:
      "patient-personal-data-form, patient-contacts, patient-healthcard, emergency-contacts, patient-review, complete-patient",
    title: "Welcome to PocketMD",
  },
  {
    description: "",
    name: "Doctor Onboarding",
    slug: "doctor",
    stepperSteps: DOCTOR_ONBOARDING_STEPS,
    stepsOrderBySlugs:
      "doctor-profile, doctor-profession, doctor-contract, doctor-review, doctor-complete",
    title: "Next Generation Health Care",
  },
];
