const DOCTOR_ONBOARDING_STEPS = [
  {
    label: "Public Profile",
    title: "Public Profile",
    description: "",
    component: "profile",
    slug: "profile",
    isFinal: false,
    order: 0,
  },
  {
    label: "Professional Information",
    title: "Professional Information",
    description: "",
    component: "profession",
    slug: "profession",
    isFinal: false,
    order: 1,
  },
  {
    label: "Review and Confirm",
    title: "Review and Confirm",
    description: "",
    component: "review",
    slug: "review",
    isFinal: true,
    order: 2,
  },
  {
    label: "Complete",
    title: "Complete",
    description: "",
    component: "final",
    slug: "final",
    isFinal: true,
    order: 3,
  },
]

const PATIENT_ONBOARDING_STEPS = [
  {
    label: "Personal Information",
    title: "Personal Information",
    description: "",
    component: "personal-data-form",
    slug: "personal-data-form",
    isFinal: false,
    order: 0,
  },
  {
    label: "Contact Information",
    title: "Contact Information",
    description: "",
    component: "contacts",
    slug: "contacts",
    isFinal: false,
    order: 1,
  },
  {
    label: "Add Health Card Information",
    title: "Add Health Card Information",
    description: "",
    component: "healthcard",
    slug: "healthcard",
    isFinal: false,
    order: 2,
  },
  {
    label: "Review & Confirm",
    title: "Review & Confirm",
    description: "",
    component: "review",
    slug: "review",
    isFinal: true,
    order: 3,
  },
  {
    label: "Done",
    title: "You are all set and ready to book doctors!",
    description: "",
    component: "final",
    slug: "final",
    isFinal: true,
    order: 4,
  },
]


export const STEPPERS = [
  { 
    label: "Welcome to PocketMD",
    title: "Welcome to PocketMD",
    name: "Patient onboarding",
    description: "",
    slug: "patient",
    stepperSteps: PATIENT_ONBOARDING_STEPS,
  },
  { 
    label: "Next Generation Health Care",
    title: "Next Generation Health Care",
    name: "Doctor Onboarding",
    description: "",
    slug: "doctor",
    stepperSteps: DOCTOR_ONBOARDING_STEPS,
  },
];