export const DUMMY_USERS = [
  // Patient Users
  {
    id: "0-patient",
    doctor: {
      // 
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y3",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: "pat-0@example.com",
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M5J 2H2",
    dateOfBirth: "2000-12-21T18:12:21.313Z",
    firstName: "P.A.T.I.E.N.T. [1]",
    lastName: "L.A.D.O.",
    password:"123123123",
    sex: "male",
    username:"UserPatient-0"
  },
  {
    id: "1-patient",
    doctor: {
      // 
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y2",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: null,
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M5J 2H2",
    dateOfBirth: "2000-12-21T18:12:21.313Z",
    firstName: "P.A.T.I.E.N.T. [0]",
    lastName: "L.A.D.O.",
    password:"123123123",
    sex: "male",
    username:"UserPatient-1"
  },
  {
    id: "2-patient",
    doctor: {
      // 
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y1",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: null,
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M5J 2H2",
    dateOfBirth: "2000-12-21T18:12:21.313Z",
    firstName: "P.A.T.I.E.N.T. [2]",
    lastName: "L.A.D.O.",
    password:"123123123",
    sex: "male",
    username:"UserPatient-2"
  },
  // Doctor Users
  {
    id: "0-doctor",
    doctor: {
      doctorSince: "2004-07-05T00:00:00.000Z",
      insuranceProvider: "RBC",
      insurancePolicyNumber: "666",
      isCompleteProfile: true,
      isVerified: true,
      licensedBy: "CPSO",
      licenseNumber: "777",
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y4",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: "doc-0@example.com",
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M8J 1A1",
    dateOfBirth: "1985-02-03T18:12:21.313Z",
    firstName: "D.O.C.T.O.R. [0]",
    lastName: "D.O.C.T.O.R.Y.",
    password:"123123123",
    sex: "male",
    username:"UserDoctor-0"
  },
  {
    id: "1-doctor",
    doctor: {
      doctorSince: "2005-07-05T00:00:00.000Z",
      insuranceProvider: "RBC",
      insurancePolicyNumber: "666",
      isCompleteProfile: true,
      isVerified: true,
      licensedBy: "CPSO",
      licenseNumber: "777",
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y5",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: null,
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M8J 1A1",
    dateOfBirth: "1985-02-03T18:12:21.313Z",
    firstName: "D.O.C.T.O.R. [1]",
    lastName: "D.O.C.T.O.R.Y.",
    password:"123123123",
    sex: "male",
    username:"UserDoctor-1"
  },
  {
    id: "2-doctor",
    doctor: {
      doctorSince: "2006-07-05T00:00:00.000Z",
      insuranceProvider: "RBC",
      insurancePolicyNumber: "666",
      isCompleteProfile: true,
      isVerified: true,
      licensedBy: "CPSO",
      licenseNumber: "777",
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y6",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: null,
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M8J 1A1",
    dateOfBirth: "1985-02-03T18:12:21.313Z",
    firstName: "D.O.C.T.O.R. [2]",
    lastName: "D.O.C.T.O.R.Y.",
    password:"123123123",
    sex: "female",
    username:"UserDoctor-2"
  },
  {
    id: "3-doctor",
    doctor: {
      doctorSince: "2007-07-05T00:00:00.000Z",
      insuranceProvider: "RBC",
      insurancePolicyNumber: "666",
      isCompleteProfile: true,
      isVerified: true,
      licensedBy: "CPSO",
      licenseNumber: "777",
    },
    patient: {
      isCompleteProfile: true,
      healthCards: {
        dateOfBirth: "",
        expiryDate: "2027-07-07",
        insurancePolicyNumber: "666",
        insuranceProvider: "RBC",
        isVerified: true,
        nameOnCard: null,
        versionCode: "Y7",
      },
      emergencyContacts: {
        email: "dummy@example.co",
        relation: "Brother",
        firstName: "John",
        lastName: "Flow",
        cellPhoneNumberString: "4163334444",
      }
    },
    isDummy: true,
    cellPhoneNumberString: "",
    homePhoneNumberString: "",
    email: null,
    country: "CA",
    administrativeArea: "ON",
    locality: "Toronto",
    postalCode: "M8J 1A1",
    dateOfBirth: "1985-02-03T18:12:21.313Z",
    firstName: "D.O.C.T.O.R. [3]",
    lastName: "D.O.C.T.O.R.Y.",
    password:"123123123",
    sex: "female",
    username:"UserDoctor-3"
  },
];