export const SPECIALTIES = [
  { label: "Anatomical Pathology",
    value: "anatomical-pathology",
  },
  { label: "Anesthesiology",
    value: "anesthesiology",
  },
  { label: "Cardiac Surgery",
    value: "cardiac-surgery",
  },
  { label: "Dermatology",
    value: "dermatology",
  },
  { label: "Diagnostic Radiology",
    value: "diagnostic-radiology",
  },
  { label: "Emergency Medicine",
    value: "emergency-medicine",
  },
  { label: "Family Medicine",
    value: "family-medicine",
  },
  { label: "General Pathology",
    value: "general-pathology",
  },
  { label: "General Surgery",
    value: "general-surgery",
  },
  { label: "Hermatological Pathology",
    value: "hermatological-pathology",
  },
  { label: "Internal Medicine",
    value: "internal-medicine",
  },
  { label: "Medical Genetics and Genomics",
    value: "medical-genetics-and-genomics",
  },
  { label: "Medical Microbiology",
    value: "medical-microbiology",
  },
  { label: "Neurosurgery",
    value: "neurosurgery",
  },
  { label: "Neurology",
    value: "neurology",
  },
  { label: "Neuropathology",
    value: "neuropathology",
  },
  { label: "Nuclear Medicine",
    value: "nuclear-medicine",
  },
  { label: "Obstetrics and Gynecology",
    value: "obstetrics-and-gynecology",
  },
  { label: "Ophthalmology",
    value: "ophthalmology",
  },
  { label: "Orthopedic Surgery",
    value: "orthopedic-surgery",
  },
  { label: "Otolaryngology-Head and Neck Surgery",
    value: "otolaryngology-head-and-neck-surgery",
  },
  { label: "Pediactrics",
    value: "pediactrics",
  },
  { label: "Physical Medicine and Rehabilitation",
    value: "physical-medicine-and-rehabilitation",
  },
  { label: "Plastic Surgery",
    value: "plastic-surgery",
  },
  { label: "Psychiatry",
    value: "psychiatry",
  },
  { label: "Public Health and Preventative Medicine",
    value: "public-health-and-preventative-medicine",
  },
  { label: "Radiation Oncology",
    value: "radiation-oncology",
  },
  { label: "Urology",
    value: "urology",
  },
  { label: "Vascular Surgery",
    value: "vascular-surgery",
  },
];