export const FORM_IMAGING_X_RAY_TESTS = [
  {
    label: 'AC Joint - Left',
    testFor: 'imaging-x-ray',
    value: 'ac-joint-left',
  },
  {
    label: 'AC Joint - Right',
    testFor: 'imaging-x-ray',
    value: 'ac-joint-right',
  },
  { label: 'Acute ABD', testFor: 'imaging-x-ray', value: 'acute-abd' },
  { label: 'Adenoids', testFor: 'imaging-x-ray', value: 'adenoids' },
  { label: 'Ankle - Left', testFor: 'imaging-x-ray', value: 'ankle-left' },
  { label: 'Ankle - Right', testFor: 'imaging-x-ray', value: 'ankle-right' },
  {
    label: 'Bone Age, Hand & Wrist - Left',
    testFor: 'imaging-x-ray',
    value: 'bone-age-hand-wrist-left',
  },
  {
    label: 'Bone Age, Hand & Wrist - Right',
    testFor: 'imaging-x-ray',
    value: 'bone-age-hand-wrist-right',
  },
  {
    label: 'Cervical Spine',
    testFor: 'imaging-x-ray',
    value: 'cervical-spine',
  },
  { label: 'Chest PA ', testFor: 'imaging-x-ray', value: 'chest-pa' },
  { label: 'Chest PA & Lat', testFor: 'imaging-x-ray', value: 'chest-pa-lat' },
  {
    label: 'Clavicle - Left',
    testFor: 'imaging-x-ray',
    value: 'clavicle-left',
  },
  {
    label: 'Clavicle - Right',
    testFor: 'imaging-x-ray',
    value: 'clavicle-right',
  },
  { label: 'Elbow - Left', testFor: 'imaging-x-ray', value: 'elbow-left' },
  { label: 'Elbow - Right', testFor: 'imaging-x-ray', value: 'elbow-right' },
  { label: 'Facial Bones', testFor: 'imaging-x-ray', value: 'facial-bones' },
  { label: 'Femur - Left', testFor: 'imaging-x-ray', value: 'femur-left' },
  { label: 'Femur - Right', testFor: 'imaging-x-ray', value: 'femur-right' },
  {
    label: 'Finger D1 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d1-left',
  },
  {
    label: 'Finger D1 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d1-left',
  },
  {
    label: 'Finger D1 - Right',
    testFor: 'imaging-x-ray',
    value: 'finger-d1-right',
  },
  {
    label: 'Finger D2 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d2-left',
  },
  {
    label: 'Finger D2 - Right',
    testFor: 'imaging-x-ray',
    value: 'finger-d2-right',
  },
  {
    label: 'Finger D3 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d3-left',
  },
  {
    label: 'Finger D3 - Right',
    testFor: 'imaging-x-ray',
    value: 'finger-d3-right',
  },
  {
    label: 'Finger D4 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d4-left',
  },
  {
    label: 'Finger D4 - Right',
    testFor: 'imaging-x-ray',
    value: 'finger-d4-right',
  },
  {
    label: 'Finger D5 - Left',
    testFor: 'imaging-x-ray',
    value: 'finger-d5-left',
  },
  {
    label: 'Finger D5 - Right',
    testFor: 'imaging-x-ray',
    value: 'finger-d5-right',
  },
  { label: 'Foot - Left', testFor: 'imaging-x-ray', value: 'foot-left' },
  { label: 'Foot - Right', testFor: 'imaging-x-ray', value: 'foot-right' },
  { label: 'Forearm - Left', testFor: 'imaging-x-ray', value: 'forearm-left' },
  {
    label: 'Forearm - Right',
    testFor: 'imaging-x-ray',
    value: 'forearm-right',
  },
  { label: 'Hip - Left', testFor: 'imaging-x-ray', value: 'hip-left' },
  { label: 'Hip - Right', testFor: 'imaging-x-ray', value: 'hip-right' },
  { label: 'Humerus - Left', testFor: 'imaging-x-ray', value: 'humerus-left' },
  {
    label: 'Humerus - Right',
    testFor: 'imaging-x-ray',
    value: 'humerus-right',
  },
  { label: 'Knee - Left', testFor: 'imaging-x-ray', value: 'knee-left' },
  { label: 'Knee - Right', testFor: 'imaging-x-ray', value: 'knee-right' },
  { label: 'KUB', testFor: 'imaging-x-ray', value: 'kub' },
  { label: 'Lumbar Spine', testFor: 'imaging-x-ray', value: 'lumbar-spine' },
  { label: 'Mandible', testFor: 'imaging-x-ray', value: 'mandible' },
  { label: 'Nasal Bones', testFor: 'imaging-x-ray', value: 'nasal-bones' },
  {
    label: 'Neck (Soft Tissue)',
    testFor: 'imaging-x-ray',
    value: 'neck-soft-tissue',
  },
  { label: 'Orbits ', testFor: 'imaging-x-ray', value: 'orbits' },
  {
    label: 'Orbits for Foreign Body',
    testFor: 'imaging-x-ray',
    value: 'orbits-for-foreign-body',
  },
  {
    label: 'OS Calcis - Left',
    testFor: 'imaging-x-ray',
    value: 'os-calcis-left',
  },
  {
    label: 'OS Calcis - Right',
    testFor: 'imaging-x-ray',
    value: 'os-calcis-right',
  },
  { label: 'Pelvis', testFor: 'imaging-x-ray', value: 'pelvis' },
  { label: 'Pelvis & Hips', testFor: 'imaging-x-ray', value: 'pelvis-hips' },
  {
    label: 'Ribs & Chest PA - Left',
    testFor: 'imaging-x-ray',
    value: 'ribs-chest-pa-left',
  },
  {
    label: 'Ribs & Chest PA - Right',
    testFor: 'imaging-x-ray',
    value: 'ribs-chest-pa-right',
  },
  {
    label: 'Sacroiliac Joints',
    testFor: 'imaging-x-ray',
    value: 'sacroiliac-joints',
  },
  {
    label: 'Sacrum / Coccyx',
    testFor: 'imaging-x-ray',
    value: 'sacrum-coccyx',
  },
  {
    label: 'Scaphoid - Left',
    testFor: 'imaging-x-ray',
    value: 'scaphoid-left',
  },
  {
    label: 'Scaphoid - Right',
    testFor: 'imaging-x-ray',
    value: 'scaphoid-right',
  },
  { label: 'Scapula - Left', testFor: 'imaging-x-ray', value: 'scapula-left' },
  {
    label: 'Scapula - Right',
    testFor: 'imaging-x-ray',
    value: 'scapula-right',
  },
  {
    label: 'Shoulder - Left',
    testFor: 'imaging-x-ray',
    value: 'shoulder-left',
  },
  {
    label: 'Shoulder - Right',
    testFor: 'imaging-x-ray',
    value: 'shoulder-right',
  },
  {
    label: 'Skeletal Survey',
    testFor: 'imaging-x-ray',
    value: 'skeletal-survey',
  },
  { label: 'Skull', testFor: 'imaging-x-ray', value: 'skull' },
  { label: 'Sternum', testFor: 'imaging-x-ray', value: 'sternum' },
  {
    label: 'Thoracic Spine',
    testFor: 'imaging-x-ray',
    value: 'thoracic-spine',
  },
  { label: 'TIB/FIB - Left', testFor: 'imaging-x-ray', value: 'tib-fib-left' },
  {
    label: 'TIB/FIB - Right',
    testFor: 'imaging-x-ray',
    value: 'tib-fib-right',
  },
  { label: 'TM Joints', testFor: 'imaging-x-ray', value: 'tm-joints' },
  { label: 'Toe D1 - Left', testFor: 'imaging-x-ray', value: 'toe-d1-left' },
  { label: 'Toe D1 - Right', testFor: 'imaging-x-ray', value: 'toe-d1-right' },
  { label: 'Toe D2 - Left', testFor: 'imaging-x-ray', value: 'toe-d2-left' },
  { label: 'Toe D2 - Right', testFor: 'imaging-x-ray', value: 'toe-d2-right' },
  { label: 'Toe D3 - Left', testFor: 'imaging-x-ray', value: 'toe-d3-left' },
  { label: 'Toe D3 - Right', testFor: 'imaging-x-ray', value: 'toe-d3-right' },
  { label: 'Toe D4 - Left', testFor: 'imaging-x-ray', value: 'toe-d4-left' },
  { label: 'Toe D4 - Right', testFor: 'imaging-x-ray', value: 'toe-d4-right' },
  { label: 'Toe D5 - Left', testFor: 'imaging-x-ray', value: 'toe-d5-left' },
  { label: 'Toe D5 - Right', testFor: 'imaging-x-ray', value: 'toe-d5-right' },
  { label: 'Wrist - Left', testFor: 'imaging-x-ray', value: 'wrist-left' },
  { label: 'Wrist - Right', testFor: 'imaging-x-ray', value: 'wrist-right' },
];
