export const FORM_PUBLIC_HEALTH_TEST_REASONS = [
  { label: 'Diagnostic', value: 'diagnostic' },
  { label: 'Needle Stick', value: 'needle-stick' },
  { label: 'Prenatal', value: 'prenatal' },
  { label: 'Immunocompromised', value: 'immunocompromised' },
  { label: 'Post-Mortem', value: 'post-mortem' },
  { label: 'Immune Status', value: 'immune-status' },
  { label: 'Follow-Up', value: 'follow-up' },
  { label: 'Chronic Condition', value: 'chronic-condition' },
  { label: 'Fever', value: 'fever' },
  { label: 'STI', value: 'sti' },
  { label: 'Pregnant', value: 'pregnant' },
  { label: 'Jaundice', value: 'jaundice' },
  { label: 'Gastroenteritis', value: 'gastroenteritis' },
  { label: 'Headache / Stiff Neck', value: 'headache-stiff-neck' },
  { label: 'Encephalitis / Meningitis', value: 'encephalitis-meningitis' },
  { label: 'Respiratory Symptoms', value: 'respiratory-symptoms' },
  { label: 'Vesicular Rash', value: 'vesicular-rash' },
  { label: 'Maculopapular Rash', value: 'maculopapular-rash' },
];
