/* eslint-disable sort-keys */
export const FORM_HIV_ORIGIN = [
  { label: 'Afghanistan', value: 'afghanistan', testFor: 'hiv-origin' },
  { label: 'Albania', value: 'albania', testFor: 'hiv-origin' },
  { label: 'Algeria', value: 'algeria', testFor: 'hiv-origin' },
  { label: 'Andorra', value: 'andorra', testFor: 'hiv-origin' },
  { label: 'Angola', value: 'angola', testFor: 'hiv-origin' },
  {
    label: 'Antigua and Barbuda',
    value: 'antigua and Barbuda',
    testFor: 'hiv-origin',
  },
  { label: 'Argentina', value: 'argentina', testFor: 'hiv-origin' },
  { label: 'Armenia', value: 'armenia', testFor: 'hiv-origin' },
  { label: 'Australia', value: 'australia', testFor: 'hiv-origin' },
  { label: 'Austria', value: 'austria', testFor: 'hiv-origin' },
  { label: 'Azerbaijan', value: 'azerbaijan', testFor: 'hiv-origin' },
  { label: 'Bahamas', value: 'bahamas', testFor: 'hiv-origin' },
  { label: 'Bahrain', value: 'bahrain', testFor: 'hiv-origin' },
  { label: 'Bangladesh', value: 'bangladesh', testFor: 'hiv-origin' },
  { label: 'Barbados', value: 'barbados', testFor: 'hiv-origin' },
  { label: 'Belarus', value: 'belarus', testFor: 'hiv-origin' },
  { label: 'Belgium', value: 'belgium', testFor: 'hiv-origin' },
  { label: 'Belize', value: 'belize', testFor: 'hiv-origin' },
  { label: 'Benin', value: 'benin', testFor: 'hiv-origin' },
  { label: 'Bhutan', value: 'bhutan', testFor: 'hiv-origin' },
  { label: 'Bolivia', value: 'bolivia', testFor: 'hiv-origin' },
  {
    label: 'Bosnia and Herzegovina',
    value: 'bosnia and Herzegovina',
    testFor: 'hiv-origin',
  },
  { label: 'Botswana', value: 'botswana', testFor: 'hiv-origin' },
  { label: 'Brazil', value: 'brazil', testFor: 'hiv-origin' },
  { label: 'Brunei', value: 'brunei', testFor: 'hiv-origin' },
  { label: 'Bulgaria', value: 'bulgaria', testFor: 'hiv-origin' },
  { label: 'Burkina Faso', value: 'burkina Faso', testFor: 'hiv-origin' },
  { label: 'Burundi', value: 'burundi', testFor: 'hiv-origin' },
  { label: "Côte d'Ivoire", value: "côte d'Ivoire", testFor: 'hiv-origin' },
  { label: 'Cabo Verde', value: 'cabo Verde', testFor: 'hiv-origin' },
  { label: 'Cambodia', value: 'cambodia', testFor: 'hiv-origin' },
  { label: 'Cameroon', value: 'cameroon', testFor: 'hiv-origin' },
  { label: 'Canada', value: 'canada', testFor: 'hiv-origin' },
  {
    label: 'Central African Republic',
    value: 'central African Republic',
    testFor: 'hiv-origin',
  },
  { label: 'Chad', value: 'chad', testFor: 'hiv-origin' },
  { label: 'Chile', value: 'chile', testFor: 'hiv-origin' },
  { label: 'China', value: 'china', testFor: 'hiv-origin' },
  { label: 'Colombia', value: 'colombia', testFor: 'hiv-origin' },
  { label: 'Comoros', value: 'comoros', testFor: 'hiv-origin' },
  {
    label: 'Congo (Congo-Brazzaville)',
    value: 'congo (Congo-Brazzaville)',
    testFor: 'hiv-origin',
  },
  { label: 'Costa Rica', value: 'costa Rica', testFor: 'hiv-origin' },
  { label: 'Croatia', value: 'croatia', testFor: 'hiv-origin' },
  { label: 'Cuba', value: 'cuba', testFor: 'hiv-origin' },
  { label: 'Cyprus', value: 'cyprus', testFor: 'hiv-origin' },
  {
    label: 'Czechia (Czech Republic)',
    value: 'czechia (Czech Republic)',
    testFor: 'hiv-origin',
  },
  {
    label: 'Democratic Republic of the Congo',
    value: 'democratic Republic of the Congo',
    testFor: 'hiv-origin',
  },
  { label: 'Denmark', value: 'denmark', testFor: 'hiv-origin' },
  { label: 'Djibouti', value: 'djibouti', testFor: 'hiv-origin' },
  { label: 'Dominica', value: 'dominica', testFor: 'hiv-origin' },
  {
    label: 'Dominican Republic',
    value: 'dominican Republic',
    testFor: 'hiv-origin',
  },
  { label: 'Ecuador', value: 'ecuador', testFor: 'hiv-origin' },
  { label: 'Egypt', value: 'egypt', testFor: 'hiv-origin' },
  { label: 'El Salvador', value: 'el Salvador', testFor: 'hiv-origin' },
  {
    label: 'Equatorial Guinea',
    value: 'equatorial Guinea',
    testFor: 'hiv-origin',
  },
  { label: 'Eritrea', value: 'eritrea', testFor: 'hiv-origin' },
  { label: 'Estonia', value: 'estonia', testFor: 'hiv-origin' },
  {
    label: "Eswatini (fmr. 'Swaziland')",
    value: "eswatini (fmr. 'Swaziland')",
    testFor: 'hiv-origin',
  },
  { label: 'Ethiopia', value: 'ethiopia', testFor: 'hiv-origin' },
  { label: 'Fiji', value: 'fiji', testFor: 'hiv-origin' },
  { label: 'Finland', value: 'finland', testFor: 'hiv-origin' },
  { label: 'France', value: 'france', testFor: 'hiv-origin' },
  { label: 'Gabon', value: 'gabon', testFor: 'hiv-origin' },
  { label: 'Gambia', value: 'gambia', testFor: 'hiv-origin' },
  { label: 'Georgia', value: 'georgia', testFor: 'hiv-origin' },
  { label: 'Germany', value: 'germany', testFor: 'hiv-origin' },
  { label: 'Ghana', value: 'ghana', testFor: 'hiv-origin' },
  { label: 'Greece', value: 'greece', testFor: 'hiv-origin' },
  { label: 'Grenada', value: 'grenada', testFor: 'hiv-origin' },
  { label: 'Guatemala', value: 'guatemala', testFor: 'hiv-origin' },
  { label: 'Guinea', value: 'guinea', testFor: 'hiv-origin' },
  { label: 'Guinea-Bissau', value: 'guinea-Bissau', testFor: 'hiv-origin' },
  { label: 'Guyana', value: 'guyana', testFor: 'hiv-origin' },
  { label: 'Haiti', value: 'haiti', testFor: 'hiv-origin' },
  { label: 'Holy See', value: 'holy See', testFor: 'hiv-origin' },
  { label: 'Honduras', value: 'honduras', testFor: 'hiv-origin' },
  { label: 'Hungary', value: 'hungary', testFor: 'hiv-origin' },
  { label: 'Iceland', value: 'iceland', testFor: 'hiv-origin' },
  { label: 'India', value: 'india', testFor: 'hiv-origin' },
  { label: 'Indonesia', value: 'indonesia', testFor: 'hiv-origin' },
  { label: 'Iran', value: 'iran', testFor: 'hiv-origin' },
  { label: 'Iraq', value: 'iraq', testFor: 'hiv-origin' },
  { label: 'Ireland', value: 'ireland', testFor: 'hiv-origin' },
  { label: 'Israel', value: 'israel', testFor: 'hiv-origin' },
  { label: 'Italy', value: 'italy', testFor: 'hiv-origin' },
  { label: 'Jamaica', value: 'jamaica', testFor: 'hiv-origin' },
  { label: 'Japan', value: 'japan', testFor: 'hiv-origin' },
  { label: 'Jordan', value: 'jordan', testFor: 'hiv-origin' },
  { label: 'Kazakhstan', value: 'kazakhstan', testFor: 'hiv-origin' },
  { label: 'Kenya', value: 'kenya', testFor: 'hiv-origin' },
  { label: 'Kiribati', value: 'kiribati', testFor: 'hiv-origin' },
  { label: 'Kuwait', value: 'kuwait', testFor: 'hiv-origin' },
  { label: 'Kyrgyzstan', value: 'kyrgyzstan', testFor: 'hiv-origin' },
  { label: 'Laos', value: 'laos', testFor: 'hiv-origin' },
  { label: 'Latvia', value: 'latvia', testFor: 'hiv-origin' },
  { label: 'Lebanon', value: 'lebanon', testFor: 'hiv-origin' },
  { label: 'Lesotho', value: 'lesotho', testFor: 'hiv-origin' },
  { label: 'Liberia', value: 'liberia', testFor: 'hiv-origin' },
  { label: 'Libya', value: 'libya', testFor: 'hiv-origin' },
  { label: 'Liechtenstein', value: 'liechtenstein', testFor: 'hiv-origin' },
  { label: 'Lithuania', value: 'lithuania', testFor: 'hiv-origin' },
  { label: 'Luxembourg', value: 'luxembourg', testFor: 'hiv-origin' },
  { label: 'Madagascar', value: 'madagascar', testFor: 'hiv-origin' },
  { label: 'Malawi', value: 'malawi', testFor: 'hiv-origin' },
  { label: 'Malaysia', value: 'malaysia', testFor: 'hiv-origin' },
  { label: 'Maldives', value: 'maldives', testFor: 'hiv-origin' },
  { label: 'Mali', value: 'mali', testFor: 'hiv-origin' },
  { label: 'Malta', value: 'malta', testFor: 'hiv-origin' },
  {
    label: 'Marshall Islands',
    value: 'marshall Islands',
    testFor: 'hiv-origin',
  },
  { label: 'Mauritania', value: 'mauritania', testFor: 'hiv-origin' },
  { label: 'Mauritius', value: 'mauritius', testFor: 'hiv-origin' },
  { label: 'Mexico', value: 'mexico', testFor: 'hiv-origin' },
  { label: 'Micronesia', value: 'micronesia', testFor: 'hiv-origin' },
  { label: 'Moldova', value: 'moldova', testFor: 'hiv-origin' },
  { label: 'Monaco', value: 'monaco', testFor: 'hiv-origin' },
  { label: 'Mongolia', value: 'mongolia', testFor: 'hiv-origin' },
  { label: 'Montenegro', value: 'montenegro', testFor: 'hiv-origin' },
  { label: 'Morocco', value: 'morocco', testFor: 'hiv-origin' },
  { label: 'Mozambique', value: 'mozambique', testFor: 'hiv-origin' },
  {
    label: 'Myanmar (formerly Burma)',
    value: 'myanmar (formerly Burma)',
    testFor: 'hiv-origin',
  },
  { label: 'Namibia', value: 'namibia', testFor: 'hiv-origin' },
  { label: 'Nauru', value: 'nauru', testFor: 'hiv-origin' },
  { label: 'Nepal', value: 'nepal', testFor: 'hiv-origin' },
  { label: 'Netherlands', value: 'netherlands', testFor: 'hiv-origin' },
  { label: 'New Zealand', value: 'new Zealand', testFor: 'hiv-origin' },
  { label: 'Nicaragua', value: 'nicaragua', testFor: 'hiv-origin' },
  { label: 'Niger', value: 'niger', testFor: 'hiv-origin' },
  { label: 'Nigeria', value: 'nigeria', testFor: 'hiv-origin' },
  { label: 'North Korea', value: 'north Korea', testFor: 'hiv-origin' },
  { label: 'North Macedonia', value: 'north Macedonia', testFor: 'hiv-origin' },
  { label: 'Norway', value: 'norway', testFor: 'hiv-origin' },
  { label: 'Oman', value: 'oman', testFor: 'hiv-origin' },
  { label: 'Pakistan', value: 'pakistan', testFor: 'hiv-origin' },
  { label: 'Palau', value: 'palau', testFor: 'hiv-origin' },
  { label: 'Palestine State', value: 'palestine State', testFor: 'hiv-origin' },
  { label: 'Panama', value: 'panama', testFor: 'hiv-origin' },
  {
    label: 'Papua New Guinea',
    value: 'papua New Guinea',
    testFor: 'hiv-origin',
  },
  { label: 'Paraguay', value: 'paraguay', testFor: 'hiv-origin' },
  { label: 'Peru', value: 'peru', testFor: 'hiv-origin' },
  { label: 'Philippines', value: 'philippines', testFor: 'hiv-origin' },
  { label: 'Poland', value: 'poland', testFor: 'hiv-origin' },
  { label: 'Portugal', value: 'portugal', testFor: 'hiv-origin' },
  { label: 'Qatar', value: 'qatar', testFor: 'hiv-origin' },
  { label: 'Romania', value: 'romania', testFor: 'hiv-origin' },
  { label: 'Russia', value: 'russia', testFor: 'hiv-origin' },
  { label: 'Rwanda', value: 'rwanda', testFor: 'hiv-origin' },
  {
    label: 'Saint Kitts and Nevis',
    value: 'saint Kitts and Nevis',
    testFor: 'hiv-origin',
  },
  { label: 'Saint Lucia', value: 'saint Lucia', testFor: 'hiv-origin' },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'saint Vincent and the Grenadines',
    testFor: 'hiv-origin',
  },
  { label: 'Samoa', value: 'samoa', testFor: 'hiv-origin' },
  { label: 'San Marino', value: 'san Marino', testFor: 'hiv-origin' },
  {
    label: 'Sao Tome and Principe',
    value: 'sao Tome and Principe',
    testFor: 'hiv-origin',
  },
  { label: 'Saudi Arabia', value: 'saudi Arabia', testFor: 'hiv-origin' },
  { label: 'Senegal', value: 'senegal', testFor: 'hiv-origin' },
  { label: 'Serbia', value: 'serbia', testFor: 'hiv-origin' },
  { label: 'Seychelles', value: 'seychelles', testFor: 'hiv-origin' },
  { label: 'Sierra Leone', value: 'sierra Leone', testFor: 'hiv-origin' },
  { label: 'Singapore', value: 'singapore', testFor: 'hiv-origin' },
  { label: 'Slovakia', value: 'slovakia', testFor: 'hiv-origin' },
  { label: 'Slovenia', value: 'slovenia', testFor: 'hiv-origin' },
  { label: 'Solomon Islands', value: 'solomon Islands', testFor: 'hiv-origin' },
  { label: 'Somalia', value: 'somalia', testFor: 'hiv-origin' },
  { label: 'South Africa', value: 'south Africa', testFor: 'hiv-origin' },
  { label: 'South Korea', value: 'south Korea', testFor: 'hiv-origin' },
  { label: 'South Sudan', value: 'south Sudan', testFor: 'hiv-origin' },
  { label: 'Spain', value: 'spain', testFor: 'hiv-origin' },
  { label: 'Sri Lanka', value: 'sri Lanka', testFor: 'hiv-origin' },
  { label: 'Sudan', value: 'sudan', testFor: 'hiv-origin' },
  { label: 'Suriname', value: 'suriname', testFor: 'hiv-origin' },
  { label: 'Sweden', value: 'sweden', testFor: 'hiv-origin' },
  { label: 'Switzerland', value: 'switzerland', testFor: 'hiv-origin' },
  { label: 'Syria', value: 'syria', testFor: 'hiv-origin' },
  { label: 'Tajikistan', value: 'tajikistan', testFor: 'hiv-origin' },
  { label: 'Tanzania', value: 'tanzania', testFor: 'hiv-origin' },
  { label: 'Thailand', value: 'thailand', testFor: 'hiv-origin' },
  { label: 'Timor-Leste', value: 'timor-Leste', testFor: 'hiv-origin' },
  { label: 'Togo', value: 'togo', testFor: 'hiv-origin' },
  { label: 'Tonga', value: 'tonga', testFor: 'hiv-origin' },
  {
    label: 'Trinidad and Tobago',
    value: 'trinidad and Tobago',
    testFor: 'hiv-origin',
  },
  { label: 'Tunisia', value: 'tunisia', testFor: 'hiv-origin' },
  { label: 'Turkey', value: 'turkey', testFor: 'hiv-origin' },
  { label: 'Turkmenistan', value: 'turkmenistan', testFor: 'hiv-origin' },
  { label: 'Tuvalu', value: 'tuvalu', testFor: 'hiv-origin' },
  { label: 'Uganda', value: 'uganda', testFor: 'hiv-origin' },
  { label: 'Ukraine', value: 'ukraine', testFor: 'hiv-origin' },
  {
    label: 'United Arab Emirates',
    value: 'united Arab Emirates',
    testFor: 'hiv-origin',
  },
  { label: 'United Kingdom', value: 'united Kingdom', testFor: 'hiv-origin' },
  {
    label: 'United States of America',
    value: 'united States of America',
    testFor: 'hiv-origin',
  },
  { label: 'Uruguay', value: 'uruguay', testFor: 'hiv-origin' },
  { label: 'Uzbekistan', value: 'uzbekistan', testFor: 'hiv-origin' },
  { label: 'Vanuatu', value: 'vanuatu', testFor: 'hiv-origin' },
  { label: 'Venezuela', value: 'venezuela', testFor: 'hiv-origin' },
  { label: 'Vietnam', value: 'vietnam', testFor: 'hiv-origin' },
  { label: 'Yemen', value: 'yemen', testFor: 'hiv-origin' },
  { label: 'Zambia', value: 'zambia', testFor: 'hiv-origin' },
  { label: 'Zimbabwe', value: 'zimbabwe', testFor: 'hiv-origin' },
];
