export const DRUG_INGREDIENTS_REDUCED = [
  {
    drugCode: 99705,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99705,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '4.7',
  },
  {
    drugCode: 99705,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '8.4',
  },
  {
    drugCode: 99706,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.8',
  },
  {
    drugCode: 99711,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '0.0195',
  },
  {
    drugCode: 99712,
    ingredientName: 'DULOXETINE (DULOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 99713,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '0.0195',
  },
  {
    drugCode: 99714,
    ingredientName: 'FAMOTIDINE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99715,
    ingredientName: 'FAMOTIDINE',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99716,
    ingredientName: 'DULOXETINE (DULOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 99717,
    ingredientName: 'PAROXETINE (PAROXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99718,
    ingredientName: 'PAROXETINE (PAROXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99719,
    ingredientName: 'PAROXETINE (PAROXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 99720,
    ingredientName: 'BRIMONIDINE TARTRATE',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 99721,
    ingredientName: 'RISPERIDONE',
    strengthUnit: 'MG',
    strengthValue: '90',
  },
  {
    drugCode: 99722,
    ingredientName: 'RISPERIDONE',
    strengthUnit: 'MG',
    strengthValue: '120',
  },
  {
    drugCode: 99723,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 99723,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 99724,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99725,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99726,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99727,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '15',
  },
  {
    drugCode: 99728,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99729,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99730,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99731,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99732,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99733,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '15',
  },
  {
    drugCode: 99734,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99735,
    ingredientName: 'LENALIDOMIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99736,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '3.955',
  },
  {
    drugCode: 99737,
    ingredientName: 'CAPECITABINE',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 99738,
    ingredientName: 'CAPECITABINE',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99739,
    ingredientName: 'IODINE (ALKYL POLY ETHOXY ETHANOL - IODINE COMPLEX)',
    strengthUnit: '%',
    strengthValue: '0.5',
  },
  {
    drugCode: 99740,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.015',
  },
  {
    drugCode: 99740,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.04',
  },
  {
    drugCode: 99740,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.03',
  },
  {
    drugCode: 99740,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.015',
  },
  {
    drugCode: 99741,
    ingredientName: 'FOSTAMATINIB (FOSTAMATINIB DISODIUM)',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99742,
    ingredientName: 'FOSTAMATINIB (FOSTAMATINIB DISODIUM)',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 99743,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.184',
  },
  {
    drugCode: 99743,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.184',
  },
  {
    drugCode: 99744,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.18',
  },
  {
    drugCode: 99744,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99744,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.215',
  },
  {
    drugCode: 99744,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99744,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.25',
  },
  {
    drugCode: 99744,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99745,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.18',
  },
  {
    drugCode: 99745,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99745,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.215',
  },
  {
    drugCode: 99745,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99745,
    ingredientName: 'NORGESTIMATE',
    strengthUnit: 'MG',
    strengthValue: '0.25',
  },
  {
    drugCode: 99745,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '0.035',
  },
  {
    drugCode: 99746,
    ingredientName: 'LETROZOLE',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99754,
    ingredientName: 'BAMLANIVIMAB',
    strengthUnit: 'MG',
    strengthValue: '700',
  },
  {
    drugCode: 99755,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99756,
    ingredientName: 'IODINE (ALKYL POLY ETHOXY ETHANOL - IODINE COMPLEX)',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 99757,
    ingredientName: 'PYRITHIONE ZINC',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 99758,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99759,
    ingredientName: 'MELPHALAN (MELPHALAN HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 99761,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99762,
    ingredientName: 'SODIUM PERTECHNETATE TC-99M',
    strengthUnit: 'GBQ',
    strengthValue: '0.4',
  },
  {
    drugCode: 99763,
    ingredientName: 'AMOXICILLIN (AMOXICILLIN TRIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '250',
  },
  {
    drugCode: 99763,
    ingredientName: 'CLAVULANIC ACID (CLAVULANATE POTASSIUM)',
    strengthUnit: 'MG',
    strengthValue: '125',
  },
  {
    drugCode: 99764,
    ingredientName: 'AMOXICILLIN (AMOXICILLIN TRIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99764,
    ingredientName: 'CLAVULANIC ACID (CLAVULANATE POTASSIUM)',
    strengthUnit: 'MG',
    strengthValue: '125',
  },
  {
    drugCode: 99765,
    ingredientName: 'AMOXICILLIN (AMOXICILLIN TRIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '875',
  },
  {
    drugCode: 99765,
    ingredientName: 'CLAVULANIC ACID (CLAVULANATE POTASSIUM)',
    strengthUnit: 'MG',
    strengthValue: '125',
  },
  {
    drugCode: 99766,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '12.5',
  },
  {
    drugCode: 99766,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99767,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '12.5',
  },
  {
    drugCode: 99767,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99768,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99768,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99769,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99769,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99770,
    ingredientName: 'CITRIC ACID',
    strengthUnit: '%',
    strengthValue: '4.5',
  },
  {
    drugCode: 99771,
    ingredientName: 'CITRIC ACID',
    strengthUnit: '%',
    strengthValue: '4.5',
  },
  {
    drugCode: 99772,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99773,
    ingredientName: 'PYRIDOSTIGMINE BROMIDE',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 99774,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99775,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '0.5',
  },
  {
    drugCode: 99776,
    ingredientName: 'DIMENHYDRINATE',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 99777,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '0.6',
  },
  {
    drugCode: 99778,
    ingredientName: 'HYOSCINE BUTYLBROMIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99779,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '325',
  },
  {
    drugCode: 99780,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99781,
    ingredientName: 'LEVOFLOXACIN (LEVOFLOXACIN HEMIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '250',
  },
  {
    drugCode: 99782,
    ingredientName: 'LEVOFLOXACIN (LEVOFLOXACIN HEMIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99783,
    ingredientName: 'LEVOFLOXACIN (LEVOFLOXACIN HEMIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '750',
  },
  {
    drugCode: 99784,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '13',
  },
  {
    drugCode: 99785,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '25',
  },
  {
    drugCode: 99786,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '50',
  },
  {
    drugCode: 99787,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '75',
  },
  {
    drugCode: 99788,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '88',
  },
  {
    drugCode: 99789,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '100',
  },
  {
    drugCode: 99790,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '112',
  },
  {
    drugCode: 99791,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '125',
  },
  {
    drugCode: 99792,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '137',
  },
  {
    drugCode: 99793,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '150',
  },
  {
    drugCode: 99794,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '175',
  },
  {
    drugCode: 99795,
    ingredientName: 'LEVOTHYROXINE SODIUM',
    strengthUnit: 'MCG',
    strengthValue: '200',
  },
  {
    drugCode: 99796,
    ingredientName: 'OLOPATADINE (OLOPATADINE HYDROCHLORIDE)',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 99797,
    ingredientName: 'BACILLUS CALMETTE-GUÉRIN (BCG) - STRAIN RUSSIAN BCG-I',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99798,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99799,
    ingredientName: 'IODINE (ALKYL POLY ETHOXY ETHANOL - IODINE COMPLEX)',
    strengthUnit: '%',
    strengthValue: '0.75',
  },
  {
    drugCode: 99803,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1',
  },
  {
    drugCode: 99804,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99805,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99806,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99807,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99808,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99809,
    ingredientName: 'BENZOYL PEROXIDE',
    strengthUnit: '%',
    strengthValue: '4',
  },
  {
    drugCode: 99811,
    ingredientName: 'LORATADINE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99812,
    ingredientName: 'TOLNAFTATE',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 99813,
    ingredientName: 'DIPHENHYDRAMINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99814,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99815,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '18',
  },
  {
    drugCode: 99816,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99817,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99818,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 99819,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '80',
  },
  {
    drugCode: 99820,
    ingredientName: 'ATOMOXETINE (ATOMOXETINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99821,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99822,
    ingredientName: 'ESCITALOPRAM (ESCITALOPRAM OXALATE)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99823,
    ingredientName: 'ESCITALOPRAM (ESCITALOPRAM OXALATE)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99824,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99824,
    ingredientName: 'DEXTROMETHORPHAN HYDROBROMIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99824,
    ingredientName: 'PHENYLEPHRINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99825,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99826,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99827,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '15',
  },
  {
    drugCode: 99828,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99829,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99830,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '7.2',
  },
  {
    drugCode: 99830,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99830,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99830,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99831,
    ingredientName: 'TULATHROMYCIN',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99832,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.75',
  },
  {
    drugCode: 99833,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.2475',
  },
  {
    drugCode: 99833,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.2475',
  },
  {
    drugCode: 99834,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99834,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99835,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99835,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99836,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99836,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99837,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99837,
    ingredientName: 'DEXTROMETHORPHAN HYDROBROMIDE',
    strengthUnit: 'MG',
    strengthValue: '15',
  },
  {
    drugCode: 99838,
    ingredientName: 'METHOTREXATE (METHOTREXATE DISODIUM)',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99839,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 99840,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99841,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 99842,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '80',
  },
  {
    drugCode: 99843,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99844,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 99845,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '120',
  },
  {
    drugCode: 99846,
    ingredientName: 'ENOXAPARIN SODIUM',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 99847,
    ingredientName: 'BENDAMUSTINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99848,
    ingredientName: 'BENDAMUSTINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99849,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.08',
  },
  {
    drugCode: 99849,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.08',
  },
  {
    drugCode: 99850,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.057',
  },
  {
    drugCode: 99850,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.057',
  },
  {
    drugCode: 99851,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.045',
  },
  {
    drugCode: 99852,
    ingredientName: 'TOZINAMERAN',
    strengthUnit: 'MCG',
    strengthValue: '30',
  },
  {
    drugCode: 99853,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 99853,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 99854,
    ingredientName: 'DROMETRIZOLE TRISILOXANE',
    strengthUnit: '%',
    strengthValue: '7',
  },
  {
    drugCode: 99854,
    ingredientName: 'BEMOTRIZINOL',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99854,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99854,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99854,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99854,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 99854,
    ingredientName: 'ENSULIZOLE',
    strengthUnit: '%',
    strengthValue: '0.5',
  },
  {
    drugCode: 99855,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99855,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '7',
  },
  {
    drugCode: 99855,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99855,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99856,
    ingredientName: 'BENDAMUSTINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99857,
    ingredientName: 'BENDAMUSTINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99858,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 99858,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 99859,
    ingredientName: 'NIFEDIPINE',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 99860,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '0.5',
  },
  {
    drugCode: 99861,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.16',
  },
  {
    drugCode: 99861,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.16',
  },
  {
    drugCode: 99862,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99862,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99864,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 99864,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '8',
  },
  {
    drugCode: 99864,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99864,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 99865,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99865,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '15',
  },
  {
    drugCode: 99865,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99865,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 99866,
    ingredientName: 'PERACETIC ACID',
    strengthUnit: '%',
    strengthValue: '1.36',
  },
  {
    drugCode: 99866,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '5.34',
  },
  {
    drugCode: 99867,
    ingredientName: 'OXYTETRACYCLINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '1000',
  },
  {
    drugCode: 99868,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99868,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 99868,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99868,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '2.75',
  },
  {
    drugCode: 99869,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '0.55',
  },
  {
    drugCode: 99874,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 99874,
    ingredientName: 'OCTINOXATE',
    strengthUnit: '%',
    strengthValue: '6.5',
  },
  {
    drugCode: 99874,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99874,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 99875,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 99875,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 99875,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99875,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '3.5',
  },
  {
    drugCode: 99876,
    ingredientName: 'FREMANEZUMAB',
    strengthUnit: 'MG',
    strengthValue: '225',
  },
  {
    drugCode: 99877,
    ingredientName: 'CITRIC ACID',
    strengthUnit: '%',
    strengthValue: '2.78',
  },
  {
    drugCode: 99879,
    ingredientName: 'LIDOCAINE HYDROCHLORIDE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 99880,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 99881,
    ingredientName: 'PHENYLEPHRINE HYDROCHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.25',
  },
  {
    drugCode: 99887,
    ingredientName: 'PILOCARPINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99888,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99889,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '12.5',
  },
  {
    drugCode: 99889,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99890,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 99890,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99891,
    ingredientName: 'HYDROCHLOROTHIAZIDE',
    strengthUnit: 'MG',
    strengthValue: '12.5',
  },
  {
    drugCode: 99891,
    ingredientName: 'OLMESARTAN MEDOXOMIL',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99892,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99893,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.36',
  },
  {
    drugCode: 99893,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.24',
  },
  {
    drugCode: 99894,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.3',
  },
  {
    drugCode: 99894,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99894,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 99894,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 99895,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.29',
  },
  {
    drugCode: 99896,
    ingredientName: 'FROVATRIPTAN (FROVATRIPTAN SUCCINATE)',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 99897,
    ingredientName: 'ONASEMNOGENE ABEPARVOVEC',
    strengthUnit: 'VG',
    strengthValue: '20000000000000',
  },
  {
    drugCode: 99899,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99899,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 99900,
    ingredientName: 'BENZETHONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.3',
  },
  {
    drugCode: 99901,
    ingredientName: 'MICONAZOLE NITRATE',
    strengthUnit: 'MG',
    strengthValue: '23',
  },
  {
    drugCode: 99901,
    ingredientName: 'PREDNISOLONE ACETATE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99901,
    ingredientName: 'POLYMYXIN B SULFATE',
    strengthUnit: 'MG',
    strengthValue: '0.5293',
  },
  {
    drugCode: 99902,
    ingredientName: 'MECASERMIN',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99903,
    ingredientName: 'OCTREOTIDE (OCTREOTIDE ACETATE)',
    strengthUnit: 'MCG',
    strengthValue: '50',
  },
  {
    drugCode: 99904,
    ingredientName: 'OCTREOTIDE (OCTREOTIDE ACETATE)',
    strengthUnit: 'MCG',
    strengthValue: '100',
  },
  {
    drugCode: 99905,
    ingredientName: 'OCTREOTIDE (OCTREOTIDE ACETATE)',
    strengthUnit: 'MCG',
    strengthValue: '500',
  },
  {
    drugCode: 99906,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1212',
  },
  {
    drugCode: 99906,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0909',
  },
  {
    drugCode: 99906,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0364',
  },
  {
    drugCode: 99906,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0545',
  },
  {
    drugCode: 99907,
    ingredientName: 'RIZATRIPTAN (RIZATRIPTAN BENZOATE)',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99908,
    ingredientName: 'RIZATRIPTAN (RIZATRIPTAN BENZOATE)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99909,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '0.6',
  },
  {
    drugCode: 99910,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1',
  },
  {
    drugCode: 99911,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.26',
  },
  {
    drugCode: 99912,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '4.5',
  },
  {
    drugCode: 99912,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '4.5',
  },
  {
    drugCode: 99913,
    ingredientName: 'BISACODYL',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 99914,
    ingredientName: 'BENZOYL PEROXIDE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 99915,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0545',
  },
  {
    drugCode: 99915,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1212',
  },
  {
    drugCode: 99915,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0364',
  },
  {
    drugCode: 99915,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0909',
  },
  {
    drugCode: 99916,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99917,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '4.5',
  },
  {
    drugCode: 99918,
    ingredientName: 'BUSPIRONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 99919,
    ingredientName: 'PIRFENIDONE',
    strengthUnit: 'MG',
    strengthValue: '267',
  },
  {
    drugCode: 99920,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.3',
  },
  {
    drugCode: 99920,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.3',
  },
  {
    drugCode: 99921,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '650',
  },
  {
    drugCode: 99921,
    ingredientName: 'DEXTROMETHORPHAN HYDROBROMIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99921,
    ingredientName: 'CHLORPHENIRAMINE MALEATE',
    strengthUnit: 'MG',
    strengthValue: '4',
  },
  {
    drugCode: 99921,
    ingredientName: 'ASCORBIC ACID',
    strengthUnit: 'MG',
    strengthValue: '250',
  },
  {
    drugCode: 99921,
    ingredientName: 'CAFFEINE',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 99922,
    ingredientName: 'OSELTAMIVIR (OSELTAMIVIR PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '6',
  },
  {
    drugCode: 99923,
    ingredientName: 'FAMOTIDINE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99924,
    ingredientName: 'FAMOTIDINE',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 99925,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99925,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99926,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 99927,
    ingredientName: 'ELASOMERAN',
    strengthUnit: 'MG',
    strengthValue: '0.2',
  },
  {
    drugCode: 99928,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99929,
    ingredientName: 'CETIRIZINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 99930,
    ingredientName: 'DUPILUMAB',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 99931,
    ingredientName: 'LIDOCAINE HYDROCHLORIDE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 99932,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '7.6',
  },
  {
    drugCode: 99932,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '4.9',
  },
  {
    drugCode: 99932,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.8',
  },
  {
    drugCode: 99933,
    ingredientName: 'ZINC OXIDE',
    strengthUnit: '%',
    strengthValue: '9',
  },
  {
    drugCode: 99933,
    ingredientName: 'OCTINOXATE',
    strengthUnit: '%',
    strengthValue: '7.5',
  },
  {
    drugCode: 99934,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.9',
  },
  {
    drugCode: 99934,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '4.3',
  },
  {
    drugCode: 99934,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '4.9',
  },
  {
    drugCode: 99934,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '9.5',
  },
  {
    drugCode: 99935,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1',
  },
  {
    drugCode: 99935,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1',
  },
  {
    drugCode: 99936,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.26',
  },
  {
    drugCode: 99937,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '3.5',
  },
  {
    drugCode: 99937,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '3.5',
  },
  {
    drugCode: 99938,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.045',
  },
  {
    drugCode: 99938,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.045',
  },
  {
    drugCode: 99939,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99939,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99940,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '51.7',
  },
  {
    drugCode: 99941,
    ingredientName: 'RIVAROXABAN',
    strengthUnit: 'MG',
    strengthValue: '103.4',
  },
  {
    drugCode: 99942,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 99943,
    ingredientName: 'AZACITIDINE',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 99944,
    ingredientName: 'AZACITIDINE',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 99945,
    ingredientName: 'RANOLAZINE',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 99946,
    ingredientName: 'RANOLAZINE',
    strengthUnit: 'MG',
    strengthValue: '1000',
  },
  {
    drugCode: 99947,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '1.627',
  },
  {
    drugCode: 99947,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.814',
  },
  {
    drugCode: 99947,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.814',
  },
  {
    drugCode: 99947,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '2.17',
  },
  {
    drugCode: 99948,
    ingredientName: 'TRETINOIN',
    strengthUnit: '%',
    strengthValue: '0.05',
  },
  {
    drugCode: 99949,
    ingredientName: 'OSELTAMIVIR (OSELTAMIVIR PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 99950,
    ingredientName: 'OSELTAMIVIR (OSELTAMIVIR PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '45',
  },
  {
    drugCode: 99951,
    ingredientName: 'OSELTAMIVIR (OSELTAMIVIR PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '75',
  },
  {
    drugCode: 99952,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '3.955',
  },
  {
    drugCode: 99953,
    ingredientName: 'INFLIXIMAB',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 99954,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '20.32',
  },
  {
    drugCode: 99954,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '15.24',
  },
  {
    drugCode: 99954,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '7.62',
  },
  {
    drugCode: 99954,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '7.62',
  },
  {
    drugCode: 99955,
    ingredientName: 'ALANINE',
    strengthUnit: 'G',
    strengthValue: '1.4',
  },
  {
    drugCode: 99955,
    ingredientName: 'ARGININE',
    strengthUnit: 'G',
    strengthValue: '1.2',
  },
  {
    drugCode: 99955,
    ingredientName: 'GLYCINE',
    strengthUnit: 'G',
    strengthValue: '1.1',
  },
  {
    drugCode: 99955,
    ingredientName: 'HISTIDINE',
    strengthUnit: 'G',
    strengthValue: '0.3',
  },
  {
    drugCode: 99955,
    ingredientName: 'ISOLEUCINE',
    strengthUnit: 'G',
    strengthValue: '0.5',
  },
  {
    drugCode: 99955,
    ingredientName: 'LEUCINE',
    strengthUnit: 'G',
    strengthValue: '0.74',
  },
  {
    drugCode: 99955,
    ingredientName: 'LYSINE (L-LYSINE ACETATE)',
    strengthUnit: 'G',
    strengthValue: '0.66',
  },
  {
    drugCode: 99955,
    ingredientName: 'METHIONINE',
    strengthUnit: 'G',
    strengthValue: '0.43',
  },
  {
    drugCode: 99955,
    ingredientName: 'PHENYLALANINE',
    strengthUnit: 'G',
    strengthValue: '0.51',
  },
  {
    drugCode: 99955,
    ingredientName: 'PROLINE',
    strengthUnit: 'G',
    strengthValue: '1.12',
  },
  {
    drugCode: 99955,
    ingredientName: 'SERINE',
    strengthUnit: 'G',
    strengthValue: '0.65',
  },
  {
    drugCode: 99955,
    ingredientName: 'TAURINE',
    strengthUnit: 'G',
    strengthValue: '0.1',
  },
  {
    drugCode: 99955,
    ingredientName: 'THREONINE',
    strengthUnit: 'G',
    strengthValue: '0.44',
  },
  {
    drugCode: 99955,
    ingredientName: 'TRYPTOPHAN',
    strengthUnit: 'G',
    strengthValue: '0.2',
  },
  {
    drugCode: 99955,
    ingredientName: 'TYROSINE',
    strengthUnit: 'G',
    strengthValue: '0.04',
  },
  {
    drugCode: 99955,
    ingredientName: 'VALINE',
    strengthUnit: 'G',
    strengthValue: '0.62',
  },
  {
    drugCode: 99956,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '7.6',
  },
  {
    drugCode: 99956,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '4.9',
  },
  {
    drugCode: 99956,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.8',
  },
  {
    drugCode: 99957,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99957,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 99958,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100917,
    ingredientName: 'PEMIGATINIB',
    strengthUnit: 'MG',
    strengthValue: '4.5',
  },
  {
    drugCode: 100918,
    ingredientName: 'PEMIGATINIB',
    strengthUnit: 'MG',
    strengthValue: '9',
  },
  {
    drugCode: 100919,
    ingredientName: 'PEMIGATINIB',
    strengthUnit: 'MG',
    strengthValue: '13.5',
  },
  {
    drugCode: 100920,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100920,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100921,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100921,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100922,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 100922,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '7.5',
  },
  {
    drugCode: 100922,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 100922,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 100923,
    ingredientName: 'HEPATITIS B IMMUNOGLOBULIN (HUMAN)',
    strengthUnit: 'UNIT',
    strengthValue: '220',
  },
  {
    drugCode: 100924,
    ingredientName: 'ETONOGESTREL',
    strengthUnit: 'MG',
    strengthValue: '11.7',
  },
  {
    drugCode: 100924,
    ingredientName: 'ETHINYL ESTRADIOL',
    strengthUnit: 'MG',
    strengthValue: '2.7',
  },
  {
    drugCode: 100925,
    ingredientName: 'TRETINOIN',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 100926,
    ingredientName: 'BISACODYL',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 100927,
    ingredientName: 'MENTHOL',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 100927,
    ingredientName: 'LIDOCAINE HYDROCHLORIDE',
    strengthUnit: '%',
    strengthValue: '4',
  },
  {
    drugCode: 100928,
    ingredientName: 'ALCOHOL ANHYDROUS',
    strengthUnit: '%',
    strengthValue: '58',
  },
  {
    drugCode: 100929,
    ingredientName: 'CHLORINE DIOXIDE',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 100929,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 100929,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 100930,
    ingredientName: 'TETANUS IMMUNOGLOBULIN (HUMAN)',
    strengthUnit: 'UNIT',
    strengthValue: '250',
  },
  {
    drugCode: 100931,
    ingredientName: 'SOTORASIB',
    strengthUnit: 'MG',
    strengthValue: '120',
  },
  {
    drugCode: 100932,
    ingredientName: 'ESOMEPRAZOLE (ESOMEPRAZOLE MAGNESIUM)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 100933,
    ingredientName: 'ESOMEPRAZOLE (ESOMEPRAZOLE MAGNESIUM)',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 100934,
    ingredientName: 'HEPATITIS B IMMUNOGLOBULIN (HUMAN)',
    strengthUnit: 'UNIT',
    strengthValue: '110',
  },
  {
    drugCode: 100935,
    ingredientName: 'HEPATITIS B IMMUNOGLOBULIN (HUMAN)',
    strengthUnit: 'UNIT',
    strengthValue: '220',
  },
  {
    drugCode: 100936,
    ingredientName: 'COLCHICINE',
    strengthUnit: 'MG',
    strengthValue: '0.5',
  },
  {
    drugCode: 100937,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100937,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100939,
    ingredientName: 'ISOPROPYL ALCOHOL',
    strengthUnit: '%',
    strengthValue: '70',
  },
  {
    drugCode: 100939,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0192',
  },
  {
    drugCode: 100940,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '100',
  },
  {
    drugCode: 100941,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '300',
  },
  {
    drugCode: 100942,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '300',
  },
  {
    drugCode: 100943,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '300',
  },
  {
    drugCode: 100944,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '300',
  },
  {
    drugCode: 100945,
    ingredientName: 'INSULIN LISPRO',
    strengthUnit: 'UNIT',
    strengthValue: '600',
  },
  {
    drugCode: 100951,
    ingredientName: 'METFORMIN HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 100952,
    ingredientName: 'METFORMIN HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '850',
  },
  {
    drugCode: 100953,
    ingredientName: 'NIZATIDINE',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 100954,
    ingredientName: 'NIZATIDINE',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 100955,
    ingredientName: 'LINEZOLID',
    strengthUnit: 'MG',
    strengthValue: '600',
  },
  {
    drugCode: 100956,
    ingredientName: 'CHLORINE DIOXIDE',
    strengthUnit: '%',
    strengthValue: '0.05',
  },
  {
    drugCode: 100958,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100958,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100959,
    ingredientName: 'VARDENAFIL (VARDENAFIL HYDROCHLORIDE TRIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 100960,
    ingredientName: 'VARDENAFIL (VARDENAFIL HYDROCHLORIDE TRIHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 100961,
    ingredientName: 'DEXTROMETHORPHAN HYDROBROMIDE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 100961,
    ingredientName: 'PHENYLEPHRINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 100961,
    ingredientName: 'DOXYLAMINE SUCCINATE',
    strengthUnit: 'MG',
    strengthValue: '6.25',
  },
  {
    drugCode: 100967,
    ingredientName: 'BISACODYL',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 100968,
    ingredientName: 'LETROZOLE',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 100972,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100972,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100973,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 100974,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 100975,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 100976,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 100977,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 100978,
    ingredientName: 'PYRAZINAMIDE',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 100982,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100982,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100983,
    ingredientName: 'INFIGRATINIB (INFIGRATINIB PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 100984,
    ingredientName: 'INFIGRATINIB (INFIGRATINIB PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '75',
  },
  {
    drugCode: 100985,
    ingredientName: 'INFIGRATINIB (INFIGRATINIB PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 100986,
    ingredientName: 'INFIGRATINIB (INFIGRATINIB PHOSPHATE)',
    strengthUnit: 'MG',
    strengthValue: '125',
  },
  {
    drugCode: 100987,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100987,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 100988,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '6.872',
  },
  {
    drugCode: 100988,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '10.307',
  },
  {
    drugCode: 100989,
    ingredientName: 'ESOMEPRAZOLE (ESOMEPRAZOLE MAGNESIUM)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 100990,
    ingredientName: 'ESOMEPRAZOLE (ESOMEPRAZOLE MAGNESIUM)',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 100991,
    ingredientName: 'MOXIFLOXACIN (MOXIFLOXACIN HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 100992,
    ingredientName: 'BEVACIZUMAB',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 100993,
    ingredientName: 'BEVACIZUMAB',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 100994,
    ingredientName: 'DIPHENHYDRAMINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 100995,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 100996,
    ingredientName: 'CITRIC ACID',
    strengthUnit: '%',
    strengthValue: '2.63',
  },
  {
    drugCode: 100997,
    ingredientName: 'SACITUZUMAB GOVITECAN',
    strengthUnit: 'MG',
    strengthValue: '180',
  },
  {
    drugCode: 100998,
    ingredientName: 'POLYETHYLENE GLYCOL 3350',
    strengthUnit: '%',
    strengthValue: '100',
  },
  {
    drugCode: 101000,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.178',
  },
  {
    drugCode: 101000,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.178',
  },
  {
    drugCode: 101001,
    ingredientName: 'PYRITHIONE ZINC',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 101002,
    ingredientName: 'PYRITHIONE ZINC',
    strengthUnit: '%',
    strengthValue: '0.5',
  },
  {
    drugCode: 101003,
    ingredientName: 'LURBINECTEDIN',
    strengthUnit: 'MG',
    strengthValue: '4',
  },
  {
    drugCode: 101004,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.26',
  },
  {
    drugCode: 101004,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 101006,
    ingredientName: 'FOSTEMSAVIR (FOSTEMSAVIR TROMETHAMINE)',
    strengthUnit: 'MG',
    strengthValue: '600',
  },
  {
    drugCode: 101007,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '12.5',
  },
  {
    drugCode: 101007,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '8',
  },
  {
    drugCode: 101007,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101007,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101012,
    ingredientName: 'POLYETHYLENE GLYCOL 3350',
    strengthUnit: 'G',
    strengthValue: '17',
  },
  {
    drugCode: 101013,
    ingredientName: 'UPADACITINIB',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 101014,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101015,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 101015,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.15',
  },
  {
    drugCode: 101016,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 101016,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.105',
  },
  {
    drugCode: 101017,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '2.5',
  },
  {
    drugCode: 101018,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101019,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101020,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101021,
    ingredientName: 'INSULIN ASPART',
    strengthUnit: 'UNIT',
    strengthValue: '100',
  },
  {
    drugCode: 101022,
    ingredientName: 'INSULIN ASPART',
    strengthUnit: 'UNIT',
    strengthValue: '100',
  },
  {
    drugCode: 101023,
    ingredientName: 'FILGRASTIM',
    strengthUnit: 'MCG',
    strengthValue: '300',
  },
  {
    drugCode: 101024,
    ingredientName: 'FILGRASTIM',
    strengthUnit: 'MCG',
    strengthValue: '480',
  },
  {
    drugCode: 101025,
    ingredientName: 'DEXTROSE ANHYDROUS',
    strengthUnit: 'G',
    strengthValue: '41.734',
  },
  {
    drugCode: 101025,
    ingredientName: 'SODIUM CHLORIDE',
    strengthUnit: 'G',
    strengthValue: '3.507',
  },
  {
    drugCode: 101025,
    ingredientName: 'GLYCINE',
    strengthUnit: 'G',
    strengthValue: '6.756',
  },
  {
    drugCode: 101025,
    ingredientName: 'POTASSIUM CHLORIDE',
    strengthUnit: 'G',
    strengthValue: '1.94',
  },
  {
    drugCode: 101025,
    ingredientName: 'SODIUM ACETATE',
    strengthUnit: 'G',
    strengthValue: '13.125',
  },
  {
    drugCode: 101025,
    ingredientName: 'SODIUM PHOSPHATE MONOBASIC',
    strengthUnit: 'G',
    strengthValue: '0.6',
  },
  {
    drugCode: 101025,
    ingredientName: 'POTASSIUM PHOSPHATE DIBASIC',
    strengthUnit: 'G',
    strengthValue: '0.349',
  },
  {
    drugCode: 101025,
    ingredientName: 'CALCIUM D-PANTOTHENATE',
    strengthUnit: 'G',
    strengthValue: '0.012',
  },
  {
    drugCode: 101026,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0909',
  },
  {
    drugCode: 101026,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0364',
  },
  {
    drugCode: 101026,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0545',
  },
  {
    drugCode: 101026,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1212',
  },
  {
    drugCode: 101027,
    ingredientName: 'AMPROLIUM',
    strengthUnit: 'MG',
    strengthValue: '96',
  },
  {
    drugCode: 101028,
    ingredientName: 'PROPYLTHIOURACIL',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 101030,
    ingredientName: 'LURASIDONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101031,
    ingredientName: 'MACITENTAN',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101031,
    ingredientName: 'TADALAFIL',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 101032,
    ingredientName: 'LURASIDONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 101033,
    ingredientName: 'LURASIDONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 101034,
    ingredientName: 'LURASIDONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '80',
  },
  {
    drugCode: 101035,
    ingredientName: 'LURASIDONE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '120',
  },
  {
    drugCode: 101036,
    ingredientName: 'EPINEPHRINE (EPINEPHRINE BITARTRATE)',
    strengthUnit: 'MG',
    strengthValue: '1',
  },
  {
    drugCode: 101037,
    ingredientName: 'BISOPROLOL FUMARATE',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101038,
    ingredientName: 'BISOPROLOL FUMARATE',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101039,
    ingredientName: 'OLOPATADINE (OLOPATADINE HYDROCHLORIDE)',
    strengthUnit: '%',
    strengthValue: '0.1',
  },
  {
    drugCode: 101040,
    ingredientName: 'PAZOPANIB (PAZOPANIB HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 101041,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '10.8',
  },
  {
    drugCode: 101042,
    ingredientName: 'BUSULFAN',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 101043,
    ingredientName: 'IMATINIB (IMATINIB MESYLATE)',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
  {
    drugCode: 101044,
    ingredientName: 'FLUCONAZOLE',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 101045,
    ingredientName: 'IMATINIB (IMATINIB MESYLATE)',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 101046,
    ingredientName: 'ACETAMINOPHEN',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 101047,
    ingredientName: 'FEXOFENADINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '60',
  },
  {
    drugCode: 101048,
    ingredientName: 'CEPHALEXIN (CEPHALEXIN MONOHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '250',
  },
  {
    drugCode: 101049,
    ingredientName: 'CEPHALEXIN (CEPHALEXIN MONOHYDRATE)',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 101050,
    ingredientName: 'TRALOKINUMAB',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 101051,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0399',
  },
  {
    drugCode: 101051,
    ingredientName: 'CHLORHEXIDINE ACETATE',
    strengthUnit: '%',
    strengthValue: '0.0133',
  },
  {
    drugCode: 101052,
    ingredientName: 'VIRUS-LIKE PARTICLES (VLP) OF SARS-COV-2 SPIKE PROTEIN',
    strengthUnit: 'MCG',
    strengthValue: '3.75',
  },
  {
    drugCode: 101053,
    ingredientName: 'DARUNAVIR',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 101054,
    ingredientName: 'DARUNAVIR',
    strengthUnit: 'MG',
    strengthValue: '600',
  },
  {
    drugCode: 101055,
    ingredientName: 'DARUNAVIR',
    strengthUnit: 'MG',
    strengthValue: '800',
  },
  {
    drugCode: 101056,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '1.84',
  },
  {
    drugCode: 101056,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '5.25',
  },
  {
    drugCode: 101056,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '2.15',
  },
  {
    drugCode: 101056,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5.25',
  },
  {
    drugCode: 101057,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 101058,
    ingredientName: 'NOREPINEPHRINE (Norepinephrine Bitartrate Monohydrate)',
    strengthUnit: 'MG',
    strengthValue: '1',
  },
  {
    drugCode: 101059,
    ingredientName: 'HYPOCHLOROUS ACID',
    strengthUnit: '%',
    strengthValue: '0.0338',
  },
  {
    drugCode: 101060,
    ingredientName: 'MILRINONE (MILRINONE LACTATE)',
    strengthUnit: 'MG',
    strengthValue: '1',
  },
  {
    drugCode: 101061,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101061,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101061,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101061,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101062,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '1.75',
  },
  {
    drugCode: 101062,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 101062,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '3.75',
  },
  {
    drugCode: 101062,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 101063,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 101063,
    ingredientName: 'HYPOCHLOROUS ACID',
    strengthUnit: '%',
    strengthValue: '0.01',
  },
  {
    drugCode: 101064,
    ingredientName: 'MELOXICAM',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101065,
    ingredientName: 'VENLAFAXINE (VENLAFAXINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '37.5',
  },
  {
    drugCode: 101066,
    ingredientName: 'VENLAFAXINE (VENLAFAXINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 101067,
    ingredientName: 'VENLAFAXINE (VENLAFAXINE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '75',
  },
  {
    drugCode: 101069,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 101070,
    ingredientName: 'DIPHENHYDRAMINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 101071,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0909',
  },
  {
    drugCode: 101071,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0364',
  },
  {
    drugCode: 101071,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.0545',
  },
  {
    drugCode: 101071,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.1212',
  },
  {
    drugCode: 101072,
    ingredientName: 'PIPERACILLIN (PIPERACILLIN SODIUM)',
    strengthUnit: 'G',
    strengthValue: '36',
  },
  {
    drugCode: 101072,
    ingredientName: 'TAZOBACTAM (TAZOBACTAM SODIUM)',
    strengthUnit: 'G',
    strengthValue: '4.5',
  },
  {
    drugCode: 101073,
    ingredientName: 'EMTRICITABINE',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 101073,
    ingredientName: 'TENOFOVIR DISOPROXIL FUMARATE',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 101074,
    ingredientName: 'ATORVASTATIN (ATORVASTATIN CALCIUM)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101075,
    ingredientName: 'ATORVASTATIN (ATORVASTATIN CALCIUM)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101076,
    ingredientName: 'ATORVASTATIN (ATORVASTATIN CALCIUM)',
    strengthUnit: 'MG',
    strengthValue: '40',
  },
  {
    drugCode: 101077,
    ingredientName: 'ATORVASTATIN (ATORVASTATIN CALCIUM)',
    strengthUnit: 'MG',
    strengthValue: '80',
  },
  {
    drugCode: 101079,
    ingredientName: 'KETOROLAC TROMETHAMINE',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 101081,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '2.3',
  },
  {
    drugCode: 101081,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 101081,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101081,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101082,
    ingredientName: 'ABIRATERONE ACETATE',
    strengthUnit: 'MG',
    strengthValue: '500',
  },
  {
    drugCode: 101083,
    ingredientName: 'ABIRATERONE ACETATE',
    strengthUnit: 'MG',
    strengthValue: '1000',
  },
  {
    drugCode: 101084,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '1.75',
  },
  {
    drugCode: 101084,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '2.5',
  },
  {
    drugCode: 101084,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 101084,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '3.75',
  },
  {
    drugCode: 101087,
    ingredientName: 'SOMATROGON',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101088,
    ingredientName: 'SODIUM HYPOCHLORITE',
    strengthUnit: '%',
    strengthValue: '4.7',
  },
  {
    drugCode: 101089,
    ingredientName: 'SOMATROGON',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 101090,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.333',
  },
  {
    drugCode: 101090,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.075',
  },
  {
    drugCode: 101091,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 101094,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 101095,
    ingredientName: 'FESOTERODINE FUMARATE',
    strengthUnit: 'MG',
    strengthValue: '4',
  },
  {
    drugCode: 101096,
    ingredientName: 'FESOTERODINE FUMARATE',
    strengthUnit: 'MG',
    strengthValue: '8',
  },
  {
    drugCode: 101097,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '2.25',
  },
  {
    drugCode: 101097,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '2.25',
  },
  {
    drugCode: 101098,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101098,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101099,
    ingredientName: 'CETIRIZINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101100,
    ingredientName: 'BORTEZOMIB (BORTEZOMIB MANNITOL BORONIC ESTER)',
    strengthUnit: 'MG',
    strengthValue: '1',
  },
  {
    drugCode: 101101,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 101102,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 101103,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '75',
  },
  {
    drugCode: 101104,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 101105,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '225',
  },
  {
    drugCode: 101106,
    ingredientName: 'PREGABALIN',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 101107,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '7.5',
  },
  {
    drugCode: 101108,
    ingredientName: 'ENFORTUMAB VEDOTIN',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101109,
    ingredientName: 'ENFORTUMAB VEDOTIN',
    strengthUnit: 'MG',
    strengthValue: '30',
  },
  {
    drugCode: 101110,
    ingredientName: 'AMBRISENTAN',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101111,
    ingredientName: 'AMBRISENTAN',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101112,
    ingredientName: 'PYRITHIONE ZINC',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 101113,
    ingredientName: 'PYRITHIONE ZINC',
    strengthUnit: '%',
    strengthValue: '1',
  },
  {
    drugCode: 101114,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.13',
  },
  {
    drugCode: 101115,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101115,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '4.08',
  },
  {
    drugCode: 101115,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101115,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '10',
  },
  {
    drugCode: 101116,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 101116,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 101117,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '5.35',
  },
  {
    drugCode: 101117,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.117',
  },
  {
    drugCode: 101118,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '1.75',
  },
  {
    drugCode: 101118,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101118,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 101118,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101119,
    ingredientName: 'DORZOLAMIDE (DORZOLAMIDE HYDROCHLORIDE)',
    strengthUnit: 'MG',
    strengthValue: '20',
  },
  {
    drugCode: 101119,
    ingredientName: 'TIMOLOL (TIMOLOL MALEATE)',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101123,
    ingredientName: 'AVOBENZONE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101123,
    ingredientName: 'HOMOSALATE',
    strengthUnit: '%',
    strengthValue: '2',
  },
  {
    drugCode: 101123,
    ingredientName: 'OCTOCRYLENE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101123,
    ingredientName: 'OCTISALATE',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101123,
    ingredientName: 'DROMETRIZOLE TRISILOXANE',
    strengthUnit: '%',
    strengthValue: '3.5',
  },
  {
    drugCode: 101123,
    ingredientName: 'BEMOTRIZINOL',
    strengthUnit: '%',
    strengthValue: '5',
  },
  {
    drugCode: 101124,
    ingredientName: 'HYDROGEN PEROXIDE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 101125,
    ingredientName: 'PENTOBARBITAL SODIUM',
    strengthUnit: 'MG',
    strengthValue: '390',
  },
  {
    drugCode: 101126,
    ingredientName: 'MONTELUKAST (MONTELUKAST SODIUM)',
    strengthUnit: 'MG',
    strengthValue: '4',
  },
  {
    drugCode: 101127,
    ingredientName: 'MONTELUKAST (MONTELUKAST SODIUM)',
    strengthUnit: 'MG',
    strengthValue: '5',
  },
  {
    drugCode: 101128,
    ingredientName: 'MONTELUKAST (MONTELUKAST SODIUM)',
    strengthUnit: 'MG',
    strengthValue: '10',
  },
  {
    drugCode: 101129,
    ingredientName: 'CHLORINE DIOXIDE',
    strengthUnit: '%',
    strengthValue: '0.2',
  },
  {
    drugCode: 101129,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 101129,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.125',
  },
  {
    drugCode: 101130,
    ingredientName: 'ALKYL DIMETHYL ETHYLBENZYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 101130,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '0.14',
  },
  {
    drugCode: 101131,
    ingredientName: 'BEVACIZUMAB',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 101132,
    ingredientName: 'BEVACIZUMAB',
    strengthUnit: 'MG',
    strengthValue: '25',
  },
  {
    drugCode: 101133,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '50',
  },
  {
    drugCode: 101134,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '150',
  },
  {
    drugCode: 101135,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 101136,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '300',
  },
  {
    drugCode: 101137,
    ingredientName: 'QUETIAPINE (QUETIAPINE FUMARATE)',
    strengthUnit: 'MG',
    strengthValue: '400',
  },
  {
    drugCode: 101138,
    ingredientName: 'MYCOPHENOLATE MOFETIL',
    strengthUnit: 'MG',
    strengthValue: '200',
  },
  {
    drugCode: 101139,
    ingredientName: 'DARUNAVIR',
    strengthUnit: 'MG',
    strengthValue: '600',
  },
  {
    drugCode: 101140,
    ingredientName: 'OCTYL DECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '3',
  },
  {
    drugCode: 101140,
    ingredientName: 'DIDECYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 101140,
    ingredientName: 'DIOCTYL DIMETHYL AMMONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '1.5',
  },
  {
    drugCode: 101140,
    ingredientName: 'BENZALKONIUM CHLORIDE',
    strengthUnit: '%',
    strengthValue: '4',
  },
  {
    drugCode: 101141,
    ingredientName: 'LIDOCAINE HYDROCHLORIDE',
    strengthUnit: 'MG',
    strengthValue: '100',
  },
];
